substitutions:
  devicename: mycollector
  mqtt_collectd_prefix: collectd
  mqtt_broker: 192.168.1.1

packages:
  area_1: !include
    file: common/mijia_package.yaml
    vars:
      area: !secret area_1_name
      area_upper: !secret area_1_upper_name
      mac_address: !secret area_1_mac_address
  area_2: !include
    file: common/mijia_package.yaml
    vars:
      area: !secret area_2_name
      area_upper: !secret area_2_upper_name
      mac_address: !secret area_2_mac_address
  area_3: !include
    file: common/mijia_package.yaml
    vars:
      area: !secret area_3_name
      area_upper: !secret area_3_upper_name
      mac_address: !secret area_3_mac_address
  # Go on adding areas
