esphome:
  name: ${devicename}

esp32:
  board: m5stack-atom
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO

# Enable our RBG LED
light:
  - platform: fastled_clockless
    chipset: SK6812
    pin: 27
    num_leds: 1
    rgb_order: GRB
    id: status_led
    name: Light

# Enable Home Assistant API
#api:
#  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Connect without scanning, required if the SSID is hidden
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_password

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    active: false

xiaomi_ble:

binary_sensor:
  - platform: gpio
    pin:
      number: 39
      inverted: true
    name: Button
    on_press:
      then:
        - if:
            condition:
              light.is_on: status_led
            then:
              light.turn_off: status_led
        - if:
            condition:
              light.is_off: status_led
            then:
              light.turn_on:
                id: status_led
                brightness: 40%
                red: 0%
                green: 100%
                blue: 0%
        - logger.log: "Button pressed"

mqtt:
  broker: $mqtt_broker
  discovery: false
